version: "3"

services:
  db:
    image: postgres:10
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_SECRET_KEY
    volumes:
      - .:/code
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - db