version: "3"

services:
  db:
    image: postgres:10
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SECRET_KEY
    volumes:
      - .:/code
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - migration
      - db
  migration:
    image: postgres:10
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - db