# Generated by Django 2.1.5 on 2019-02-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('sex', models.CharField(max_length=255, verbose_name='性別')),
                ('age', models.IntegerField(verbose_name='年齢')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
