# Generated by Django 2.1.5 on 2019-02-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineschool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('basic_charge', models.IntegerField(verbose_name='基本料金')),
                ('pay_per_charge', models.IntegerField(verbose_name='従量料金')),
            ],
            options={
                'db_table': 'lesson',
            },
        ),
    ]
