# Generated by Django 2.1.5 on 2019-02-19 04:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onlineschool', '0002_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField(default=django.utils.timezone.now, verbose_name='受講日')),
                ('lesson_hour', models.TimeField(default=django.utils.timezone.now, verbose_name='受講時間')),
                ('lesson_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineschool.Lesson', verbose_name='ジャンル名')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineschool.User', verbose_name='顧客名')),
            ],
            options={
                'db_table': 'lessonrecord',
            },
        ),
    ]
