# Generated by Django 2.1.5 on 2019-02-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineschool', '0003_lessonrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrecord',
            name='lesson_hour',
            field=models.IntegerField(default=0, verbose_name='受講時間'),
        ),
    ]
