# Generated by Django 2.1.5 on 2019-02-19 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onlineschool', '0005_auto_20190219_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonrecord',
            old_name='lesson_hour',
            new_name='lesson_term',
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='lesson_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='受講日'),
        ),
    ]
