# Generated by Django 2.1.5 on 2019-02-19 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineschool', '0006_auto_20190219_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonrecord',
            old_name='lesson_term',
            new_name='lesson_hour',
        ),
    ]
