# Generated by Django 2.1.5 on 2019-02-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineschool', '0010_discount_free_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='free_time',
        ),
        migrations.AddField(
            model_name='lesson',
            name='free_time',
            field=models.IntegerField(default=0, verbose_name='無料時間'),
        ),
    ]
