# Generated by Django 2.1.5 on 2019-02-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineschool', '0011_auto_20190224_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrecord',
            name='lesson_charge',
            field=models.IntegerField(default=0, verbose_name='受講料金'),
        ),
    ]
